Resources:
  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "terraform-state-${AWS::Region}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: "Enabled"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
  LockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "terraform-state-lock"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "LockID"
          KeyType: "HASH"
Outputs:
  BucketName:
    Value: !Ref StateBucket
    Export:
      Name: "TerraformStateBucketName"
  LockTableName:
    Value: !Ref LockTable
    Export:
      Name: "TerraformLockTableName"